### ISSUE TITLE
undefined reference to '__device_dts_ord_X'

### ISSUE THREAD

**Issue by purpl3F0x** [nobodyguy/HX711_zephyr_driver#6]
Hello, I'm trying to use the driver on NCS 2.4.0 , but I get the following error:
`C:\Users\Stavros\Documents\bike-powermeter\cycling_powermeter\src\main.c:89: undefined reference to '__device_dts_ord_8\' `

My app.overlay looks liks so:
```rust
/{
        aliases {
		hx711-sensor = &hx711;
	};

	hx711: hx711 {
		compatible = "avia,hx711";
		status = "okay";
		dout-gpios = <&gpio0 3 (GPIO_ACTIVE_HIGH | GPIO_PULL_UP) >;
		sck-gpios = <&gpio0 4 GPIO_ACTIVE_HIGH>;
	};
};
```

Kconfig
```c
CONFIG_SENSOR=y
CONFIG_HX711=y
CONFIG_GPIO=y
```

The only modification I have is putting the files directly into the project - not using west.yml.

**Comment by nobodyguy** [comment]
Hello Stavros,
thank you for the report. NCS 2.4.0 (Zephyr v3.4.0-rc1) is not supported right now.
I can add the support in the following days, but it's possible that it won't fix your issue.
In that case, access to your project (f.e. as a private Github repo) would be great to investigate the configuration.

**Comment by purpl3F0x** [comment]
Hello @nobodyguy, thanks for the quick reply, I upload the project as a zip, because I haven't uploaded to GH yet

[cycling_powermeter.zip](https://github.com/nobodyguy/HX711_zephyr_driver/files/12169456/cycling_powermeter.zip)

**Comment by purpl3F0x** [comment]
small update: I tried building with NCS 2.3.0 and still gettings the same issue

**Comment by purpl3F0x** [comment]
I was able to resolve the issue by adding `zephyr_sources(hx711.c)` in the CMakeLists.txt
